### ISSUE TITLE
MVP - List of fitness exercises

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#1]
**Value proposition:**
As a user
i want to create a fitness plan with exercises for a specific session
to have an overview of the current workout session and the exercises i want to do next

**Description:**
Singlepage application, which lets you search for exercises by fetching to an API. You can add every single exercise from the result to your workout session.

**Wireframe:**
![Bildschirmfoto 2023-05-16 um 16 16 17](https://github.com/JohannSiemens/capstone-project/assets/120959810/ddb22ac2-0b13-4a5d-896d-1becbbce9300)

**Acceptance criteria:**
- [ ] Searchbar with user input for exercise search
- [ ] "Search"-Button which executes the user input
- [ ] Click on the Search-Button fetches data with the user input against an exercise API
- [ ] Fetched exercises are being displayed in a list
- [ ] Every fetched exercise has an "Add" Button
- [ ] Exercise is being added to the workout after user clicks the "Add"-Button
- [ ] All exercises which are added to the workout should be displayed in a list

**Tasks:**
- [ ] create branch
- [ ] fetch test-data from the API
- [ ] check fetched data for display solution of the exercises
- [ ] write tests
