### ISSUE TITLE
Editing and deleting workouts

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#13]
This is a split up from this [US](https://github.com/JohannSiemens/capstone-project/issues/3), because it turned out to be too big in terms of lines of code.

### **Value proposition:**

As a user
i want to edit and delete my workouts
to have a better overview over my schedule and the exercises within the workouts.

### **Wireframe:**
![Bildschirmfoto 2023-05-18 um 18 10 18](https://github.com/JohannSiemens/capstone-project/assets/120959810/f22e4909-023b-4d6b-b923-3204c175fc56)

### **Acceptance criteria:**

- [x] There is an "edit"-button and a "delete"-button for each workout
- [x] When the user clicks the "edit"-button he can change the name of the workout
- [x] When the user clicks the "delete"-button the workout is being deleted

### **Tasks:**

- [x] Create branch
- [ ] Write tests
- [x] Implement the edit button from the exercises and give it the workout key as a prop
- [x] Implement the delete button from the exercises and give it the workout key as a prop

**Comment by JohannSiemens** [comment]
Successfully merged to main!
