### ISSUE TITLE
Design, styling & accessibility (Workout screen)

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#16]
### **Value proposition:**

As a developer
i want my application to have a uniformly and appealing styling throughout every component
to be able to fulfill the user requirements in terms of visualization.

As a user
i want the application i use to look appealing to me and fulfill the requirements to a certain user experience standard
to be able to use the application frequently and intuitively.

### **Acceptance criteria:**

- [ ] The application should be accessible
- [ ] The styling should be uniformly (e.g. colors, generell styling concept)
- [ ] The design should take the user experience and workflows into account
- [ ] All features should still work, as they did before the styling

### **Tasks:**

- [ ] Create branch
- [ ] Write tests
- [ ] Create high level overview of potential components to style & a design concept
- [ ] Create styled components based on the design concept

**Comment by JohannSiemens** [comment]
Decided to keep the styling small and only implemented the basics for the first "Workout" screen.

Not done, open for next US:

Implementation of styling for further screens
Refactoring of editing state (also in the workout screen) still needed
Accessibility is also going to be part of a different US

**Comment by JohannSiemens** [comment]
Feedback from QA:

<img width="384" alt="Bildschirmfoto 2023-06-12 um 09 18 23" src="https://github.com/JohannSiemens/capstone-project/assets/120959810/cce747c2-9e51-461d-9c84-6ca828aa12a6">

As mentioned in the previous comment, this is part of the next US, so as PO i am deciding to keep this as planned.

**Comment by JohannSiemens** [comment]
Merged successfully.
