### ISSUE TITLE
Styling (& refactoring) for further screens

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#18]
This is basically a clone of [US8](https://github.com/JohannSiemens/capstone-project/issues/16) to implement further styling throughout the rest of the application. The previous US got too big in terms of lines of code, so i had to split the user story.

### **Value proposition:**

As a developer
i want my application to have a uniformly and appealing styling throughout every component
to be able to fulfill the user requirements in terms of visualization.

As a user
i want the application i use to look appealing to me and fulfill the requirements to a certain user experience standard
to be able to use the application frequently and intuitively.

### **Acceptance criteria:**

- [ ] The application should be accessible
- [x] The styling should be uniformly (e.g. colors, generell styling concept)
- [x] The design should take the user experience and workflows into account
- [x] All features should still work, as they did before the styling

### **Tasks:**

- [x] Create branch
- [ ] Write tests
- [x] Implement the styled components for the further screens (the exercises overview within the workout)
- [x] Refactor the "card component" for the workouts overview into a "form" (edit mode) and a "section" (display mode) within the list-item

**Comment by JohannSiemens** [comment]
PR & QA for the refactoring of the workout-card component is done and merged!

**Comment by JohannSiemens** [comment]
QA done and merged successfully!
