### ISSUE TITLE
Creating, editing and deleting workout plans

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#2]
### **Value proposition:**

As a user
i want to create workout plans which contain all my workouts
to be able to track a whole cycle of different workouts for a specific goal

As a user
i want to edit and delete my workout plans
to have a better overview over my schedule and the workouts.

### **Wireframe:**
![Bildschirmfoto 2023-05-19 um 09 06 36](https://github.com/JohannSiemens/capstone-project/assets/120959810/9cf9bc65-6bae-492f-b6ad-d3717ceefaab)

### **Acceptance criteria:**

- [ ] A "back"-Button is shown in the "My Workouts" overview
- [ ] If the user clicks the "back"-Button he is being directed to a "My Workout Plans" page
- [ ] The "My Workout Plans" Page shows the current workout plan with a default name for the workout plan
- [ ] There is an "edit"-button and a "delete"-button for each workout plan
- [ ] When the user clicks the "edit"-button he can change the name of the workout plan
- [ ] When the user clicks the "delete"-button the workout plan is being deleted
- [ ] Below the current workout plans there is an input field and an "Add"-Button
- [ ] The user can write a workout plan name into the input field
- [ ] If the user clicks the "Add"-Button the workout plan with the input name is being created
- [ ] If the user clicks on an added workout plan, then he gets to the "My Workouts" overview with his workouts for this workout plan

### **Tasks:**

- [ ] Create branch
- [ ] Write tests
- [ ] Create a "My Workout Plans" page with the current workout plan named "My Workout Plan"
- [ ] Implement the edit button from the exercises and give it the workout plan key as a prop
- [ ] Implement the delete button from the exercises and give it the workout plan key as a prop
- [ ] Implement an on-click event for every workout plan which routes the user to the "My Workouts" page for the specific workout plan
- [ ] Create an input field on the "My Workout Plans" page and an "Add"-button
- [ ] Create a "back"-button on the "My Workouts" page with on on-click event to direct the user to the "My Workout Plans" page
