### ISSUE TITLE
Adding sets & repetitions

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#2]
### **Value proposition:**

As a user
i want to add sets and repetitions to my exercises
to be able to keep track of the details of every single exercise.

### **Wireframe:**

![Bildschirmfoto 2023-05-17 um 16 54 30](https://github.com/JohannSiemens/capstone-project/assets/120959810/993a7f0c-3958-4ebd-a9ef-ca2af39b22d9)

### **Acceptance criteria:**
- [ ] Every added exercise should have a fold and unfold function with an icon for each to switch between the "folded" and "unfolded" state
- [ ] When the user clicks the exercise it unfolds and shows a "Sets" and a "Repetitions" (required) field with an "Add"-Button
- [ ] The Sets is a set number, which is being counted up (starting with 1) and the user can write numbers in the numeric field
- [ ] When the user clicks the "Add"-Button it should add the set with the repetitions to the exercise
- [ ] When the user clicked the "Add"-Button, a new field for "Sets" (in this example "Set 2") and "Repetitions" with a new "Add"-Button should appear
- [ ] When the user clicks the exercise again it folds and hides all the information
- [ ] When the user clicks the exercise again it unfolds and shows all the information

### **Tasks:**
- [ ] Create branch
- [ ] Write tests
- [ ] Create an "unfolded" State with an empty Array
- [ ] Change the added exercise card-component so it has an on-click event and one icon each to display the "folded" and "unfolded" state
- [ ] The on-click event should filter with the "key" value from the current card-component (li-element) over the unfolded State and check if the key is already in there. If it isn't, then it should add it into the state, if it is, then delete it from the state
- [ ] Create a new "sets"-component to display the Sets as <p> with a set numeric counter which is counting up, starting with 1 (e.g. Set 1), a numeric-input-field, a label for the input field with the text of "Repetitions" and an "Add"-Button
- [ ] Add the "sets"-component for each added exercise and make it folded when its not in the "unfolded" State and unfold when its in the "unfolded" state
- [ ] Within the "sets"-component, the "Add"-Button should have an on-click event, which returns a <p> with the current set (e.g. Set 1) and the numeric user input (e.g. 12) in a row and creates a new set (e.g. Set 2), a new label "Repetitions" and a new numeric-input-field with the "Add"-Button below the rendered <p> for the previous added set
