### ISSUE TITLE
Tracking weight for every set of an exercise

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#21]
### **Value proposition:**

As a user
i want to track my weights for every set of an exercise i do
to be able to see if i am getting stronger.

### **Acceptance criteria:**

- [x] There should be a numeric input field for weight for every set within an exercise
- [x] The weight should be displayed for every set, next to the repetitions field
- [x] The weight should be stored within the database

### **Tasks:**

- [x] Create branch
- [x] Change the data model to accept weight as a number value
- [x] Change the client to have an input field for weight
- [x] Change the client to display the weight from the database
- [x] Change the API to also write and read the weight for every set

**Comment by JohannSiemens** [comment]
QA feedback will be implemented in another PR, successfully merged
