### ISSUE TITLE
Editing (sets) & deleting sets and exercises

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#3]
### **Value proposition:**

As a user
i want to delete existing exercises and sets
to be able to only track those which are relevant for my workout.

As a user
i want to edit my sets for each exercise
to be able to correct them if i created them wrong.

### **Wireframe:**

![Bildschirmfoto 2023-05-18 um 08 04 11](https://github.com/JohannSiemens/capstone-project/assets/120959810/96f14534-266f-4a65-8352-c7ff7e0937e5)

### **Acceptance criteria:**

- [ ] Every added exercise should have a "Delete"-Button when it is in the "folded" State
- [ ] No added exercise should have a "Delete"-Button when it is in the "unfolded" State
- [ ] When the user clicks the "Delete"-Button for an exercise, then the exercise should be deleted from the added exercises list
- [ ] Every added Set within every added exercise should an "Edit"-Button and a "Delete"-Button
- [ ] When the user clicks the "Delete"-Button the Set should be deleted
- [ ] When the user clicks the "Edit"-Button the user should be able to edit the numeric-input-field for the repetitions

### **Tasks:**

- [ ] Create branch
- [ ] Write tests
- [ ] Create a state for the added exercises
- [ ] When the exercise is being added from the search results into the "added exercises" overview, then it should also be added to the state
- [ ] Create a "Delete"-Button which receives a "toDelete" prop and implement it to be rendered for each exercise and set
- [ ] The "Delete"-Button has an on-click event, which receives the ID of either the exercise or set and Deletes it (from the state)
- [ ] Create an "Edit"-Button which receives a "toEdit" prop and implement it to be rendered for each set
- [ ] The "Edit"-Button has an on-click event, which receives the ID of the set and then changes the rendered paragraph with the current set and repetition into a paragraph with the set and an numeric-input-field for the repetitions
- [ ] Create a "save"-Button with an on-click event which saves the edited repetitions for this set and renders it as a paragraph with the edited data
