### ISSUE TITLE
Creating workouts

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#3]
### **Value proposition:**

As a user
i want to create more than just one workout
to be able to keep track of the several workouts throughout the week/month etc.

### **Wireframe:**
![Bildschirmfoto 2023-05-18 um 18 10 18](https://github.com/JohannSiemens/capstone-project/assets/120959810/f22e4909-023b-4d6b-b923-3204c175fc56)

### **Acceptance criteria:**

- [x] A "back"-Button is shown in the "My workout" overview
- [x] If the user clicks the "back"-Button he is being directed to a "My Workouts" page
- [x] The "My Workouts" Page shows the current Workout with a default name for the workout
- [x] Below the current workouts there is an input field and an "Add"-Button
- [x] The user can write a workout name into the input field
- [x] If the user clicks the "Add"-Button the workout with the input name is being created
- [x] If the user clicks on an added workout, then he gets to the "My workout" overview with his exercises

### **Tasks:**

- [x] Create branch
- [ ] Write tests
- [x] Create a "My Workouts" page with the current workout named "My Workout"
- [x] Implement an on-click event for every workout which routes the user to the "My Workout" page for the specific workout
- [x] Create an input field on the "My Workouts" page and an "Add"-button
- [x] Create a "back"-button on the "My Workout" page

**Comment by JohannSiemens** [comment]
Talked to Merle about the comment and will keep the feature set as it is, because i am implementing the create, edit and delete feature for the sets before this one. So the feature set here will be a copy & paste into a different context.

**Comment by JohannSiemens** [comment]
Decided to split this ticket into at least 2. [Here](https://github.com/JohannSiemens/capstone-project/issues/13) is the new one. Due to the refactoring based on the new data model the lines of code got out of hand for just one ticket.

**Comment by JohannSiemens** [comment]
Successfully merged into main
