### ISSUE TITLE
Creating, editing and deleting workouts

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#4]
### **Value proposition:**

As a user
i want to create more than just one workout
to be able to keep track of the several workouts throughout the week/month etc.

As a user
i want to edit and delete my workouts
to have a better overview over my schedule and the exercises within the workouts.

### **Wireframe:**
![Bildschirmfoto 2023-05-18 um 18 10 18](https://github.com/JohannSiemens/capstone-project/assets/120959810/f22e4909-023b-4d6b-b923-3204c175fc56)

### **Acceptance criteria:**

- [ ] A "back"-Button is shown in the "My workout" overview
- [ ] If the user clicks the "back"-Button he is being directed to a "My Workouts" page
- [ ] The "My Workouts" Page shows the current Workout with a default name for the workout
- [ ] There is an "edit"-button and a "delete"-button for each workout
- [ ] When the user clicks the "edit"-button he can change the name of the workout
- [ ] When the user clicks the "delete"-button the workout is being deleted
- [ ] Below the current workouts there is an input field and an "Add"-Button
- [ ] The user can write a workout name into the input field
- [ ] If the user clicks the "Add"-Button the workout with the input name is being created
- [ ] If the user clicks on an added workout, then he gets to the "My workout" overview with his exercises

### **Tasks:**

- [ ] Create branch
- [ ] Write tests
- [ ] Create a "My Workouts" page with the current workout named "My Workout"
- [ ] Implement the edit button from the exercises and give it the workout key as a prop
- [ ] Implement the delete button from the exercises and give it the workout key as a prop
- [ ] Implement an on-click event for every workout which routes the user to the "My Workout" page for the specific workout
- [ ] Create an input field on the "My Workouts" page and an "Add"-button
- [ ] Create a "back"-button on the "My Workout" page

**Comment by MerleMak** [comment]
Hi Johann, 
I would recommend you split up this Userstory into at least 2 or maybe three Userstories :)
One for creating a new workout, one for deleting and one for editing. This will also be very helpful for the reviewer of your Pull Requests :p
