### ISSUE TITLE
Exercise Fetch API

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#6]
### **Value proposition:**

As a developer
i want to create my own API to use to fetch data from the exercise API
to be able to protect my API Key from potential stealing/manipulation via the client

### **Description:**

Creating an API for my Client to fetch against, to then fetch the Data with the API against the exercise API i use.

### **Acceptance criteria:**

- [ ] The client fetches the data without the use of an API key against my own API
- [ ] My own API uses the client side request with the API key to GET the data from the exercise API
- [ ] My own API responses to the client side request with the fetched data from the exercise API
- [ ] The client does not use or receives the API key
- [ ] My own API receives a GET from the client for a specific user input in the URL to fetch for exercises via name only (URL example: ".../exercises?name=<name>")
- [ ] My own API does only provide the GET request method

### **Tasks:**

- [ ] Create branch
- [ ] Write tests
- [ ] Create an API with GET request method only
- [ ] Implement error handling for the API
- [ ] Refactor client to fetch the data against the API

**Comment by MerleMak** [comment]
Amazing work! Great user story! 🥹
