### ISSUE TITLE
MVP - List of fitness exercises

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#6]
**Value proposition:**
As a user
i want to create a fitness plan with exercises for a specific session
to have an overview of the current workout session and the exercises i want to do next

**Description:**
Singlepage application, which lets you search for exercises by fetching to an API. You can add every single exercise from the result to your workout session.

**Wireframe:**
![Bildschirmfoto 2023-05-16 um 16 16 17](https://github.com/JohannSiemens/capstone-project/assets/120959810/87d8bb75-1375-4cbe-9815-eacae62ea8df)

**Acceptance criteria:**
- [x] Searchbar with user input for exercise search
- [x] "Search"-Button which executes the user input
- [ ] Click on the Search-Button fetches data with the user input against an exercise API
- [x] Fetched exercises are being displayed in a list
- [x] Every fetched exercise has an "Add" Button
- [x] Exercise is being added to the workout after user clicks the "Add"-Button
- [x] All exercises which are added to the workout should be displayed in a list

**Tasks:**
- [x] create branch
- [x] fetch test-data from the API
- [x] check fetched data for display solution of the response
- [x] write tests
- [x] create input-field for search and "search"-button
- [ ] search button has an on-click event to fetch data from the exercise API by using the user input (https://api.api-ninjas.com/v1/exercises?name=<userinput>)
- [x] create paragraph tag with "Can't find this exercise" text under the input-field if the API can't find the input. It should only appear if the user pressed the search-button and the API can't find the input
- [x] create card-component as a list-item-element to display the fetched object within the response-array
- [x] create a ul and map over response-array from the API to create every single object as the card-component displayed within the ul
- [x] ignore everything in the object within the response-array except for the exercise name
- [x] create a state myExercise with an empty array
- [x] create "Add"-Button within the card-component with an on-click event, which adds the object for the exercise to the state
- [x] create card-component for the added exercises
- [x] create a ul under the search result ul and map over the state array to create every single object as the card-component for the added exercises within the ul

**Comment by JohannSiemens** [comment]
Done!
