### ISSUE TITLE
Implementation of Atlas-MongoDB

### ISSUE THREAD

**Issue by JohannSiemens** [JohannSiemens/capstone-project#8]
### **Value proposition:**

As a user
i want to see my workouts even if i close the website or switch the device/browser
to be able to keep track of my workouts outside of the browser and device i am currently using.

As a developer
i want to store data consistently and long term outside of the client or the client device
to be able to reduce complexity in the client and the potential of data manipulation/theft within the client and device.

### **Description:**
Implementation of an Atlas-MongoDB to save all the relevant product data in it.

### **Acceptance criteria:**

- [x] The workout data is being stored in an Atlas MongoDB
- [x] The Data is being fetched via my own APIs into and from the Atlas MongoDB
- [x] The API key for the exercise API is securely managed by my own API
- [x] The User can see all his data when he closes the browser
- [x] The User can see all his data when he switches the browser
- [x] All the user data is consistent towards what the user did before the browser switch/close
- [x] The app still works with every feature

### **Tasks:**

- [x] Create branch
- [ ] Write tests
- [x] Create Atlas MongoDB Database
- [x] Create collections (user, workout plans, workouts, exercises) based on the first version of the data model
- [x] Create a dummy user for the plans
- [x] Create APIs for the HTTP Requests from the Client to the MongoDB
- [x] Refactor client side code to use the APIs instead of unnecessary state

**Comment by JohannSiemens** [comment]
Successfully merged!
